version: 2
updates:
  - package-ecosystem: docker
    directories:
      - /src/*
    schedule:
      interval: weekly
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
      # Patch updates are released monthly on the second Tuesday of each month, also known as Patch Tuesday
      # https://dotnet.microsoft.com/en-us/platform/support/policy
      day: wednesday
    ignore:
      - dependency-name: '*'
        update-types: 
          - version-update:semver-major
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: System.Data.SqlClient # See reason in Directory.Packages.props